import PDFDocument from 'pdfkit';
import { TrainerReport } from './trainer-report.service';

const ACCENT = '#6a18a8';
const MUTED = '#666666';
const INK = '#111111';

function formatTokens(value: string): string {
  const number = Number(value);
  return Number.isFinite(number) ? number.toLocaleString('en-US', { maximumFractionDigits: 2 }) : value;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

/**
 * Renders a TrainerReport as a one-page-plus-table PDF -- a real document
 * (text/tables via pdfkit), not a screenshot, so it stays crisp and small
 * enough to email as an attachment. Mirrors the stat grid already shown on
 * frontend/app/dashboard/reports/page.tsx, plus a daily activity table, so
 * the emailed PDF and the on-screen report never drift apart in content.
 */
export function renderTrainerReportPdf(
  report: TrainerReport,
  trainerName: string,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fillColor(ACCENT).fontSize(20).font('Helvetica-Bold').text('Dialect Library');
    doc.fillColor(INK).fontSize(14).font('Helvetica-Bold').text('Trainer account report', { paragraphGap: 4 });
    doc
      .fillColor(MUTED)
      .fontSize(10)
      .font('Helvetica')
      .text(`${trainerName} -- ${formatDate(report.from)} to ${formatDate(report.to)}`);
    doc.moveDown(1.5);

    const stats: [string, string][] = [
      ['Recordings', String(report.totals.recordings)],
      ['Scored', String(report.totals.scoredRecordings)],
      ['Avg. score', report.totals.avgScore ? `${report.totals.avgScore}%` : '—'],
      ['Training earnings', `${formatTokens(report.totals.trainingEarningsTokens)} DL`],
      ['Referral earnings', `${formatTokens(report.totals.referralEarningsTokens)} DL`],
      ['Total earned (range)', `${formatTokens(report.totals.totalEarningsTokens)} DL`],
      ['Total tokens since join', `${formatTokens(report.totals.totalTokensSinceJoin)} DL`],
      ['Available balance', `${formatTokens(report.totals.availableBalanceTokens)} DL`],
      ['Held balance', `${formatTokens(report.totals.heldBalanceTokens)} DL`],
      ['Total withdrawn', `${formatTokens(report.totals.totalWithdrawnTokens)} DL`],
    ];

    const colWidth = (doc.page.width - doc.page.margins.left - doc.page.margins.right) / 2;
    let column = 0;
    let rowTop = doc.y;
    let rowHeight = 0;
    for (const [label, value] of stats) {
      const x = doc.page.margins.left + column * colWidth;
      doc.fillColor(MUTED).fontSize(8).font('Helvetica-Bold').text(label.toUpperCase(), x, rowTop, {
        width: colWidth - 12,
      });
      doc
        .fillColor(INK)
        .fontSize(13)
        .font('Helvetica-Bold')
        .text(value, x, doc.y, { width: colWidth - 12 });
      rowHeight = Math.max(rowHeight, doc.y - rowTop);
      column += 1;
      if (column === 2) {
        column = 0;
        rowTop += rowHeight + 14;
        rowHeight = 0;
      }
    }
    doc.y = column === 0 ? rowTop : rowTop + rowHeight + 14;
    doc.moveDown(1);

    doc
      .strokeColor('#dddddd')
      .moveTo(doc.page.margins.left, doc.y)
      .lineTo(doc.page.width - doc.page.margins.right, doc.y)
      .stroke();
    doc.moveDown(1);

    doc.fillColor(INK).fontSize(12).font('Helvetica-Bold').text('Daily activity (selected range)');
    doc.moveDown(0.5);

    const tableX = doc.page.margins.left;
    const tableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const dateColWidth = tableWidth * 0.4;
    const recColWidth = tableWidth * 0.3;
    const earnColWidth = tableWidth * 0.3;

    function drawTableRow(date: string, recordings: string, earnings: string, header = false) {
      const y = doc.y;
      doc
        .fillColor(header ? MUTED : INK)
        .fontSize(9)
        .font(header ? 'Helvetica-Bold' : 'Helvetica')
        .text(date, tableX, y, { width: dateColWidth })
        .text(recordings, tableX + dateColWidth, y, { width: recColWidth, align: 'right' })
        .text(earnings, tableX + dateColWidth + recColWidth, y, { width: earnColWidth, align: 'right' });
      doc.moveDown(0.4);
    }

    drawTableRow('Date', 'Recordings', 'Earnings (DL)', true);
    for (const day of report.daily) {
      if (doc.y > doc.page.height - doc.page.margins.bottom - 20) doc.addPage();
      drawTableRow(day.date, String(day.recordings), formatTokens(day.earningsTokens));
    }

    doc.moveDown(1.5);
    doc
      .fillColor(MUTED)
      .fontSize(8)
      .font('Helvetica')
      .text('Generated by Dialect Library. For questions, contact hello@dialectlibrary.com.');

    doc.end();
  });
}
