ALTER TYPE "CommunityReactionType" ADD VALUE IF NOT EXISTS 'HAPPY';
ALTER TYPE "CommunityReactionType" ADD VALUE IF NOT EXISTS 'SMILE';
ALTER TYPE "CommunityReactionType" ADD VALUE IF NOT EXISTS 'LOL';
ALTER TYPE "CommunityReactionType" ADD VALUE IF NOT EXISTS 'SAD';
ALTER TYPE "CommunityReactionType" ADD VALUE IF NOT EXISTS 'CRY';

ALTER TABLE "community_posts"
  ADD COLUMN "happyCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "smileCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "lolCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "sadCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "cryCount" INTEGER NOT NULL DEFAULT 0;
