apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOakEwTWpJeApOalUxTXpKYUZ3MDBOakEwTWpJeE5qVTFNekphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDenA3Q2ROd05HcGl1ODA0bnJ6K3pLdHpxOHZFZlNLWGdvamt5dTNaa0xJZTJhUzV6bwo3YVlPNmpYdlVDa2lQc3R6NmNzZlNjZnJYek9BaW01VHdUN2JUUHVJSG1tYmtMQTFoVWNrV1J1R0Zha21qaGVECndHRHZkZzJreFpaMTc3Ym55RUloWXpDQWdZOGpiTG5JdUV5b0NZYTEySFYwdFhYNEd4alFiWWZwMlNpSmExVVkKNGIxNXdGZ1oyNWJzek5BWXpRaDE1czdYWnV1eXlUdC9ybWozeDQzSEFUd3BsVnlycVBYTkNJbXpneEkyTU1IOApMMXVSMDgvZGlZVEE0bWUvVVFxOU5GOTJsQlFROUNlRU0zQUdZZUkrYUZOcWlmUXBEc3laWkFlNXJ2ZkhNR0ZDCnpMRFQyT3dKWG45em9sZmJwT2RiNU0xYnZMNEYxdDUydHR1TkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJhWmdFUmhjYUh1Ny84U3NhYwpzUjNqbk9nKzVUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFKcTBab3RjaXoyTDRsWW41NzdVWWpzUWpGbDhzCitFR05aQjZWbytQV1Bqd0ZWVUFVN01yWHE0dFpIbWdzVHRWTUZQWDdocms1M2I5Y1E4SEJWV05aSHVIZEYydksKOUZFZ0tsUThkUHdYOXhkdCsvVHpleUFPQTlnaXlmWFFoQlltbXcySVFDY2tNMkY1UUJUNFV2NVRWU2RrMWl2dAozMmhMRUJkQm1mN3Z0UzkweGxaMU54SHFwNjkzM0E0b04xSXA2V0RJdEpjdHJ3eDQvcHZadkZSQjlUZXZHa280ClQzQ3dEaFBManJWSUlmc1d5aWNYc3B5VkhUTFFObTNGZG5wdnhrZ3VkbnUrSklnQUJGQjBvRVVwZHlaa25yc2YKUlc5ajRQVnluOVk0SzhhTXNrUzNkUHVlR0VzdThkTitka3VNRzBMek5BU0YrT2V4MGprSFMxWm9Xdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://467743e8-91f9-4163-80ce-c28d9c7c6a02.k8s.ondigitalocean.com
  name: do-nyc3-hosoptima-prod
contexts:
- context:
    cluster: do-nyc3-hosoptima-prod
    user: do-nyc3-hosoptima-prod-admin
  name: do-nyc3-hosoptima-prod
current-context: do-nyc3-hosoptima-prod
kind: Config
preferences: {}
users:
- name: do-nyc3-hosoptima-prod-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=hosoptima
      - 467743e8-91f9-4163-80ce-c28d9c7c6a02
      command: C:\Program Files\doctl\doctl.exe
      env: null
      provideClusterInfo: false
