'use client';

import { useEffect, useState } from 'react';
import { Search } from 'lucide-react';
import { AdminShell } from '@/components/admin/AdminShell';
import { BulkDeleteDialog } from '@/components/admin/BulkDeleteDialog';
import { ActionButton } from '@/components/ui/ActionButton';
import { resolveDialectName } from '@/lib/dialect-name';
import {
  PART_OF_SPEECH_VALUES,
  PartOfSpeech,
  normalizeErrorMessage,
  useBulkDeleteSentencesMutation,
  useBulkDeleteWordsMutation,
  useDeleteSentenceMutation,
  useDeleteWordMutation,
  useGetAdminSentencesQuery,
  useGetAdminWordsQuery,
  useGetAllDialectsQuery,
} from '@/store/api';

function formatPartOfSpeech(value: PartOfSpeech | null): string {
  if (!value) return '—';
  return value.charAt(0) + value.slice(1).toLowerCase();
}

const secondaryButtonClass =
  'inline-flex min-h-9 items-center justify-center rounded-lg border border-line bg-surface px-3 py-1.5 text-sm font-bold text-ink transition-colors hover:bg-surface-muted disabled:cursor-not-allowed disabled:opacity-60';
const dangerButtonClass =
  'inline-flex min-h-9 items-center justify-center rounded-lg border border-line bg-surface px-3 py-1.5 text-sm font-bold text-danger transition-colors hover:bg-[#fde8e8] disabled:cursor-not-allowed disabled:opacity-60';

const tabs = [
  { key: 'words', label: 'Words' },
  { key: 'sentences', label: 'Sentences' },
] as const;

type TabKey = (typeof tabs)[number]['key'];

/** Debounces a fast-changing value (e.g. every keystroke) so a search box doesn't fire a request per character. */
function useDebouncedValue<T>(value: T, delayMs: number): T {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => {
    const timer = setTimeout(() => setDebounced(value), delayMs);
    return () => clearTimeout(timer);
  }, [value, delayMs]);
  return debounced;
}

function SearchBox({
  value,
  onChange,
  placeholder,
}: {
  value: string;
  onChange: (value: string) => void;
  placeholder: string;
}) {
  return (
    <div className="relative max-w-sm">
      <Search
        className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"
        aria-hidden="true"
      />
      <input
        className="min-h-10 w-full rounded-lg border border-line bg-white py-2 pl-9 pr-3 text-sm text-ink dark:bg-surface-muted"
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        type="search"
        value={value}
        aria-label={placeholder}
      />
    </div>
  );
}

export default function AdminWordsPage() {
  const [active, setActive] = useState<TabKey>('words');

  return (
    <AdminShell>
      <div className="grid gap-6">
        <div className="grid gap-2">
          <h1 className="text-3xl font-black">Words &amp; Sentences</h1>
          <p className="leading-relaxed text-muted">
            Content generated by the word-generator-job (see Settings &rarr; Word Generation), plus
            the original hand-seeded bank. Delete a word or sentence to remove it from the
            trainer-facing pool.
          </p>
        </div>

        <div className="flex gap-1">
          {tabs.map((tab) => (
            <button
              key={tab.key}
              type="button"
              onClick={() => setActive(tab.key)}
              className={`rounded-lg px-3 py-2 text-sm font-bold transition-colors ${
                active === tab.key
                  ? 'bg-accent text-white'
                  : 'bg-white text-ink hover:bg-surface-muted'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {active === 'words' && <WordsTab />}
        {active === 'sentences' && <SentencesTab />}
      </div>
    </AdminShell>
  );
}

function WordsTab() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [partOfSpeech, setPartOfSpeech] = useState<PartOfSpeech | ''>('');
  const debouncedSearch = useDebouncedValue(search, 300);
  const pageSize = 20;
  const { data, isLoading, isFetching, isError, refetch } = useGetAdminWordsQuery({
    page,
    pageSize,
    search: debouncedSearch || undefined,
    partOfSpeech: partOfSpeech || undefined,
  });
  const [deleteWord] = useDeleteWordMutation();
  const [bulkDeleteWords] = useBulkDeleteWordsMutation();
  const [error, setError] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [bulkDialog, setBulkDialog] = useState<'selected' | 'all' | null>(null);
  const { data: dialects } = useGetAllDialectsQuery();

  useEffect(() => {
    setPage(1);
  }, [debouncedSearch, partOfSpeech]);

  useEffect(() => {
    setSelected(new Set());
  }, [debouncedSearch, partOfSpeech, page]);

  async function handleDelete(id: string) {
    setError(null);
    setDeletingId(id);
    try {
      await deleteWord(id).unwrap();
    } catch (err) {
      setError(normalizeErrorMessage(err, 'Unable to delete word.'));
    } finally {
      setDeletingId(null);
    }
  }

  function toggleSelected(id: string, checked: boolean) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (checked) next.add(id);
      else next.delete(id);
      return next;
    });
  }

  function toggleSelectAllOnPage(checked: boolean) {
    setSelected(checked ? new Set(data?.items.map((word) => word.id) ?? []) : new Set());
  }

  const allOnPageSelected = (data?.items.length ?? 0) > 0 && selected.size === data?.items.length;

  return (
    <section className="grid gap-4 overflow-hidden rounded-lg border border-line bg-white shadow-[0_2px_8px_rgba(27,31,27,0.05)]">
      <div className="flex flex-wrap items-center gap-3 border-b border-line p-3">
        <SearchBox value={search} onChange={setSearch} placeholder="Search words..." />
        <div className="flex items-center gap-2">
          <label className="text-sm font-bold" htmlFor="word-pos-filter">
            Part of speech
          </label>
          <select
            className="min-h-9 rounded-lg border border-line bg-white px-3 text-sm"
            id="word-pos-filter"
            onChange={(e) => setPartOfSpeech(e.target.value as PartOfSpeech | '')}
            value={partOfSpeech}
          >
            <option value="">All</option>
            {PART_OF_SPEECH_VALUES.map((value) => (
              <option key={value} value={value}>
                {formatPartOfSpeech(value)}
              </option>
            ))}
          </select>
        </div>
        <div className="ml-auto flex items-center gap-2">
          {selected.size > 0 && (
            <button
              className={dangerButtonClass}
              onClick={() => setBulkDialog('selected')}
              type="button"
            >
              Delete selected ({selected.size})
            </button>
          )}
          {(data?.total ?? 0) > 0 && (
            <button className={dangerButtonClass} onClick={() => setBulkDialog('all')} type="button">
              Clear All
            </button>
          )}
        </div>
      </div>

      {error && (
        <p className="px-5 leading-relaxed text-danger" role="alert">
          {error}
        </p>
      )}

      {isLoading ? (
        <p className="p-5 text-muted">Loading...</p>
      ) : isError ? (
        <div className="grid gap-3 p-5 text-center">
          <p className="font-extrabold">Could not load words.</p>
          <button className={secondaryButtonClass} onClick={() => void refetch()} type="button">
            Try again
          </button>
        </div>
      ) : data && data.items.length > 0 ? (
        <>
          <div className="hidden overflow-x-auto md:block">
            <table className="w-full min-w-180 border-collapse text-left text-sm">
              <thead className="border-b border-line bg-surface-muted text-xs font-extrabold uppercase text-muted">
                <tr>
                  <th className="w-10 px-5 py-3.5" scope="col">
                    <input
                      aria-label="Select all words on this page"
                      checked={allOnPageSelected}
                      className="size-4 accent-accent"
                      onChange={(e) => toggleSelectAllOnPage(e.target.checked)}
                      type="checkbox"
                    />
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Word
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Part of speech
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Translations
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Added
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-line">
                {data.items.map((word) => (
                  <tr key={word.id}>
                    <td className="px-5 py-3.5">
                      <input
                        aria-label={`Select ${word.text}`}
                        checked={selected.has(word.id)}
                        className="size-4 accent-accent"
                        onChange={(e) => toggleSelected(word.id, e.target.checked)}
                        type="checkbox"
                      />
                    </td>
                    <td className="px-5 py-3.5 font-extrabold">{word.text}</td>
                    <td className="px-5 py-3.5 text-muted">
                      {formatPartOfSpeech(word.partOfSpeech)}
                    </td>
                    <td className="px-5 py-3.5 text-muted">
                      {word.translations.length === 0
                        ? '—'
                        : word.translations
                            .map((t) => `${resolveDialectName(t.dialectTag, dialects)}: ${t.text}`)
                            .join(', ')}
                    </td>
                    <td className="px-5 py-3.5 text-muted">
                      {new Date(word.createdAt).toLocaleDateString()}
                    </td>
                    <td className="px-5 py-3.5">
                      <ActionButton
                        className={dangerButtonClass}
                        onClick={() => handleDelete(word.id)}
                        pending={deletingId === word.id}
                        pendingLabel="Deleting"
                        type="button"
                      >
                        Delete
                      </ActionButton>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="divide-y divide-line md:hidden">
            {data.items.map((word) => (
              <article className="grid gap-3 p-4" key={word.id}>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <input
                      aria-label={`Select ${word.text}`}
                      checked={selected.has(word.id)}
                      className="mt-1 size-4 accent-accent"
                      onChange={(e) => toggleSelected(word.id, e.target.checked)}
                      type="checkbox"
                    />
                    <div>
                      <p className="font-extrabold">{word.text}</p>
                      <p className="text-xs text-muted">{formatPartOfSpeech(word.partOfSpeech)}</p>
                    </div>
                  </div>
                  <ActionButton
                    className={dangerButtonClass}
                    onClick={() => handleDelete(word.id)}
                    pending={deletingId === word.id}
                    pendingLabel="Deleting"
                    type="button"
                  >
                    Delete
                  </ActionButton>
                </div>
                <p className="text-sm text-muted">
                  {word.translations.length === 0
                    ? 'No translations yet'
                    : word.translations
                        .map((t) => `${resolveDialectName(t.dialectTag, dialects)}: ${t.text}`)
                        .join(', ')}
                </p>
                <p className="text-xs text-muted">
                  Added {new Date(word.createdAt).toLocaleDateString()}
                </p>
              </article>
            ))}
          </div>
        </>
      ) : (
        <p className="p-5 text-muted">
          {debouncedSearch ? `No words match "${debouncedSearch}".` : 'No words yet.'}
        </p>
      )}

      {data && data.totalPages > 1 && (
        <PaginationFooter
          page={data.page}
          totalPages={data.totalPages}
          isFetching={isFetching}
          onChange={setPage}
        />
      )}

      {bulkDialog === 'selected' && (
        <BulkDeleteDialog
          description={`This permanently deletes ${selected.size} selected word${selected.size === 1 ? '' : 's'}, along with any recordings or training assignments tied to them.`}
          onClose={() => setBulkDialog(null)}
          onConfirm={async () => {
            const result = await bulkDeleteWords({ ids: [...selected] }).unwrap();
            setSelected(new Set());
            return result;
          }}
          title="Delete selected words?"
        />
      )}
      {bulkDialog === 'all' && (
        <BulkDeleteDialog
          description={`This permanently deletes all ${data?.total ?? 0} word${data?.total === 1 ? '' : 's'} matching the current search and filter, along with any recordings or training assignments tied to them.`}
          onClose={() => setBulkDialog(null)}
          onConfirm={() =>
            bulkDeleteWords({
              search: debouncedSearch || undefined,
              partOfSpeech: partOfSpeech || undefined,
            }).unwrap()
          }
          title="Clear all words?"
        />
      )}
    </section>
  );
}

function SentencesTab() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const debouncedSearch = useDebouncedValue(search, 300);
  const pageSize = 20;
  const { data, isLoading, isFetching, isError, refetch } = useGetAdminSentencesQuery({
    page,
    pageSize,
    search: debouncedSearch || undefined,
  });
  const [deleteSentence] = useDeleteSentenceMutation();
  const [bulkDeleteSentences] = useBulkDeleteSentencesMutation();
  const [error, setError] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [bulkDialog, setBulkDialog] = useState<'selected' | 'all' | null>(null);
  const { data: dialects } = useGetAllDialectsQuery();

  useEffect(() => {
    setPage(1);
  }, [debouncedSearch]);

  useEffect(() => {
    setSelected(new Set());
  }, [debouncedSearch, page]);

  async function handleDelete(id: string) {
    setError(null);
    setDeletingId(id);
    try {
      await deleteSentence(id).unwrap();
    } catch (err) {
      setError(normalizeErrorMessage(err, 'Unable to delete sentence.'));
    } finally {
      setDeletingId(null);
    }
  }

  function toggleSelected(id: string, checked: boolean) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (checked) next.add(id);
      else next.delete(id);
      return next;
    });
  }

  function toggleSelectAllOnPage(checked: boolean) {
    setSelected(checked ? new Set(data?.items.map((sentence) => sentence.id) ?? []) : new Set());
  }

  const allOnPageSelected = (data?.items.length ?? 0) > 0 && selected.size === data?.items.length;

  return (
    <section className="grid gap-4 overflow-hidden rounded-lg border border-line bg-white shadow-[0_2px_8px_rgba(27,31,27,0.05)]">
      <div className="flex flex-wrap items-center gap-3 border-b border-line p-3">
        <SearchBox value={search} onChange={setSearch} placeholder="Search sentence text..." />
        <div className="ml-auto flex items-center gap-2">
          {selected.size > 0 && (
            <button
              className={dangerButtonClass}
              onClick={() => setBulkDialog('selected')}
              type="button"
            >
              Delete selected ({selected.size})
            </button>
          )}
          {(data?.total ?? 0) > 0 && (
            <button className={dangerButtonClass} onClick={() => setBulkDialog('all')} type="button">
              Clear All
            </button>
          )}
        </div>
      </div>

      {error && (
        <p className="px-5 leading-relaxed text-danger" role="alert">
          {error}
        </p>
      )}

      {isLoading ? (
        <p className="p-5 text-muted">Loading...</p>
      ) : isError ? (
        <div className="grid gap-3 p-5 text-center">
          <p className="font-extrabold">Could not load sentences.</p>
          <button className={secondaryButtonClass} onClick={() => void refetch()} type="button">
            Try again
          </button>
        </div>
      ) : data && data.items.length > 0 ? (
        <>
          <div className="hidden overflow-x-auto md:block">
            <table className="w-full min-w-180 border-collapse text-left text-sm">
              <thead className="border-b border-line bg-surface-muted text-xs font-extrabold uppercase text-muted">
                <tr>
                  <th className="w-10 px-5 py-3.5" scope="col">
                    <input
                      aria-label="Select all sentences on this page"
                      checked={allOnPageSelected}
                      className="size-4 accent-accent"
                      onChange={(e) => toggleSelectAllOnPage(e.target.checked)}
                      type="checkbox"
                    />
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Text
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Words
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Translations
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Added
                  </th>
                  <th className="px-5 py-3.5" scope="col">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-line">
                {data.items.map((sentence) => (
                  <tr key={sentence.id}>
                    <td className="px-5 py-3.5">
                      <input
                        aria-label={`Select ${sentence.text}`}
                        checked={selected.has(sentence.id)}
                        className="size-4 accent-accent"
                        onChange={(e) => toggleSelected(sentence.id, e.target.checked)}
                        type="checkbox"
                      />
                    </td>
                    <td className="px-5 py-3.5 font-extrabold">{sentence.text}</td>
                    <td className="px-5 py-3.5 text-muted">{sentence.wordCount}</td>
                    <td className="px-5 py-3.5 text-muted">
                      {sentence.translations.length === 0
                        ? '—'
                        : sentence.translations
                            .map((t) => `${resolveDialectName(t.dialectTag, dialects)}: ${t.text}`)
                            .join(', ')}
                    </td>
                    <td className="px-5 py-3.5 text-muted">
                      {new Date(sentence.createdAt).toLocaleDateString()}
                    </td>
                    <td className="px-5 py-3.5">
                      <ActionButton
                        className={dangerButtonClass}
                        onClick={() => handleDelete(sentence.id)}
                        pending={deletingId === sentence.id}
                        pendingLabel="Deleting"
                        type="button"
                      >
                        Delete
                      </ActionButton>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="divide-y divide-line md:hidden">
            {data.items.map((sentence) => (
              <article className="grid gap-3 p-4" key={sentence.id}>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    <input
                      aria-label={`Select ${sentence.text}`}
                      checked={selected.has(sentence.id)}
                      className="mt-1 size-4 accent-accent"
                      onChange={(e) => toggleSelected(sentence.id, e.target.checked)}
                      type="checkbox"
                    />
                    <p className="text-sm">{sentence.text}</p>
                  </div>
                  <ActionButton
                    className={dangerButtonClass}
                    onClick={() => handleDelete(sentence.id)}
                    pending={deletingId === sentence.id}
                    pendingLabel="Deleting"
                    type="button"
                  >
                    Delete
                  </ActionButton>
                </div>
                <p className="text-sm text-muted">
                  {sentence.translations.length === 0
                    ? 'No translations yet'
                    : sentence.translations
                        .map((t) => `${resolveDialectName(t.dialectTag, dialects)}: ${t.text}`)
                        .join(', ')}
                </p>
                <p className="text-xs text-muted">
                  Added {new Date(sentence.createdAt).toLocaleDateString()}
                </p>
              </article>
            ))}
          </div>
        </>
      ) : (
        <p className="p-5 text-muted">
          {debouncedSearch ? `No sentences match "${debouncedSearch}".` : 'No sentences yet.'}
        </p>
      )}

      {data && data.totalPages > 1 && (
        <PaginationFooter
          page={data.page}
          totalPages={data.totalPages}
          isFetching={isFetching}
          onChange={setPage}
        />
      )}

      {bulkDialog === 'selected' && (
        <BulkDeleteDialog
          description={`This permanently deletes ${selected.size} selected sentence${selected.size === 1 ? '' : 's'}, along with any recordings or training assignments tied to them.`}
          onClose={() => setBulkDialog(null)}
          onConfirm={async () => {
            const result = await bulkDeleteSentences({ ids: [...selected] }).unwrap();
            setSelected(new Set());
            return result;
          }}
          title="Delete selected sentences?"
        />
      )}
      {bulkDialog === 'all' && (
        <BulkDeleteDialog
          description={`This permanently deletes all ${data?.total ?? 0} sentence${data?.total === 1 ? '' : 's'} matching the current search, along with any recordings or training assignments tied to them.`}
          onClose={() => setBulkDialog(null)}
          onConfirm={() => bulkDeleteSentences({ search: debouncedSearch || undefined }).unwrap()}
          title="Clear all sentences?"
        />
      )}
    </section>
  );
}

function PaginationFooter({
  page,
  totalPages,
  isFetching,
  onChange,
}: {
  page: number;
  totalPages: number;
  isFetching: boolean;
  onChange: (page: number) => void;
}) {
  return (
    <div className="flex items-center justify-between gap-3 border-t border-line bg-surface-muted px-4 py-3 md:px-5">
      <p className="text-sm text-muted">
        Page {page} of {totalPages} {isFetching ? '· refreshing…' : ''}
      </p>
      <div className="flex gap-2">
        <button
          className={secondaryButtonClass}
          disabled={page <= 1}
          onClick={() => onChange(page - 1)}
          type="button"
        >
          Previous
        </button>
        <button
          className={secondaryButtonClass}
          disabled={page >= totalPages}
          onClick={() => onChange(page + 1)}
          type="button"
        >
          Next
        </button>
      </div>
    </div>
  );
}
