import Image from 'next/image';
import Link from 'next/link';
import type { LucideIcon } from 'lucide-react';
import { ArrowRight, BarChart3, CheckCircle2, Database, FileCheck2, KeyRound, Layers3, LockKeyhole, Radio, Search, ShieldCheck, UsersRound, Webhook } from 'lucide-react';
import { BrandLogo } from '@/components/BrandLogo';
import { StreamMarketingHeader } from '@/components/StreamMarketingHeader';

const features: { icon: LucideIcon; title: string; text: string }[] = [
  { icon: Search, title: 'Voice data search', text: 'Explore eligible recordings by country, dialect, sub-dialect, language, and quality evidence.' },
  { icon: Layers3, title: 'Stream Decks', text: 'Build durable collections of validated recordings for a model, market, or research question.' },
  { icon: ShieldCheck, title: 'Independent validation', text: 'See quality signals from Dialect Library scoring and participating subscriber organizations.' },
  { icon: Database, title: 'Versioned datasets', text: 'Work from stable, versioned collections so training and evaluation stay reproducible.' },
  { icon: Radio, title: 'Secure API streaming', text: 'Deliver licensed data into your infrastructure with scoped API access and usage controls.' },
  { icon: UsersRound, title: 'Team access control', text: 'Give owners, dataset managers, validators, and billing managers the access they need.' },
];

const deckRows = [
  ['DLSD-NG-IGB-SOUTHEAST-24', 'Igbo', 'Nigeria - South East', '0.92', '124.6 hrs'],
  ['DLSD-NG-YOR-SOUTHWEST-17', 'Yoruba', 'Nigeria - South West', '0.90', '96.3 hrs'],
  ['DLSD-GH-TWI-ACCRA-08', 'Twi', 'Ghana - Greater Accra', '0.88', '78.1 hrs'],
];

export default function HomePage() {
  return (
    <main className="min-h-screen bg-[#f6f8fc] text-[#101a34]">
      <StreamMarketingHeader />

      <section className="overflow-hidden bg-[#061632] text-white">
        <div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 md:py-20 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:px-8">
          <div className="grid gap-6">
            <p className="w-fit rounded-full border border-cyan-300/30 bg-cyan-300/10 px-3 py-1.5 text-xs font-extrabold text-cyan-200">Trusted voice infrastructure for AI teams</p>
            <h1 className="max-w-xl text-4xl font-black leading-[1.08] sm:text-5xl lg:text-6xl">Secure voice data for AI systems that need to understand more people.</h1>
            <p className="max-w-xl text-base leading-relaxed text-slate-300 sm:text-lg">Search, validate, curate, and stream licensed dialect voice data into your ASR, voice assistant, and language-model workflows.</p>
            <div className="flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#147af3] px-5 py-3 font-extrabold text-white no-underline transition-colors hover:bg-[#0c60cc]" href="/register">Request access <ArrowRight aria-hidden="true" className="size-4" /></Link><Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-white/30 px-5 py-3 font-extrabold text-white no-underline transition-colors hover:bg-white/10" href="#api">Explore the API <KeyRound aria-hidden="true" className="size-4" /></Link></div>
            <div className="grid grid-cols-1 gap-3 pt-2 text-sm text-slate-200 sm:grid-cols-3"><ValueLine label="Curated coverage" value="Countries, dialects, sub-dialects" /><ValueLine label="Quality signals" value="Scoring and independent validation" /><ValueLine label="Delivery" value="Scoped API and Stream Decks" /></div>
          </div>
          <div className="relative mx-auto w-full max-w-2xl overflow-hidden rounded-xl border border-white/15 bg-[#0d244c] shadow-[0_28px_70px_rgba(0,0,0,0.35)]"><div className="relative aspect-[4/3]"><Image alt="Voice Stream catalogue and validation workspace used by an AI data professional" className="object-cover" fill priority sizes="(max-width: 1023px) calc(100vw - 48px), 52vw" src="/voice-stream-product.png" /></div><div className="absolute inset-x-0 bottom-0 grid gap-1 bg-[#061632]/90 px-4 py-3 sm:grid-cols-[1fr_auto] sm:items-center"><p className="text-sm font-bold text-white">Voice search, quality evidence, and delivery in one workspace.</p><span className="text-xs font-bold text-cyan-200">Voice Stream</span></div></div>
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-5 px-4 py-10 sm:px-6 lg:px-8" id="features">
        <div className="max-w-2xl"><p className="text-sm font-extrabold uppercase text-accent">Platform capabilities</p><h2 className="mt-2 text-3xl font-black leading-tight sm:text-4xl">Everything your team needs to use voice data responsibly.</h2></div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{features.map((feature) => { const Icon = feature.icon; return <article className="grid gap-3 rounded-lg border border-line bg-white p-5 shadow-[0_2px_8px_rgba(16,26,52,0.04)]" key={feature.title}><span className="grid size-10 place-items-center rounded-lg bg-accent-soft text-accent"><Icon aria-hidden="true" className="size-5" /></span><h3 className="text-lg font-black">{feature.title}</h3><p className="text-sm leading-relaxed text-muted">{feature.text}</p></article>; })}</div>
      </section>

      <section className="border-y border-line bg-white" id="validation"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-extrabold uppercase text-accent">How it works</p><h2 className="mt-2 text-3xl font-black leading-tight sm:text-4xl">From voice data discovery to secure model delivery.</h2></div><div className="mt-9 grid gap-5 md:grid-cols-4"><Step number="01" icon={Search} title="Search voice data" text="Find recordings that match the country, dialect, and quality requirements for your work." /><Step number="02" icon={ShieldCheck} title="Review validation" text="Inspect quality signals and independent validation evidence before selecting data." /><Step number="03" icon={Layers3} title="Build a Stream Deck" text="Save approved recordings as a named, versioned working collection for your team." /><Step number="04" icon={Radio} title="Stream to your stack" text="Use API keys, scoped access, and usage controls to deliver data into your pipeline." /></div></div></section>

      <section className="mx-auto grid max-w-7xl gap-5 px-4 py-12 sm:px-6 lg:px-8" id="stream-decks"><div className="flex flex-wrap items-end justify-between gap-4"><div className="max-w-2xl"><p className="text-sm font-extrabold uppercase text-accent">Stream Decks</p><h2 className="mt-2 text-3xl font-black leading-tight sm:text-4xl">Curated, validated collections ready for the next stage of your work.</h2></div><Link className="inline-flex items-center gap-2 text-sm font-extrabold text-accent no-underline hover:text-accent-dark" href="/register">Request access <ArrowRight aria-hidden="true" className="size-4" /></Link></div><div className="overflow-x-auto rounded-lg border border-line bg-white shadow-[0_2px_8px_rgba(16,26,52,0.04)]"><table className="min-w-[760px] w-full border-collapse text-left text-sm"><thead className="border-b border-line bg-surface-muted text-xs uppercase text-muted"><tr><th className="px-4 py-3">Deck ID</th><th className="px-4 py-3">Dialect</th><th className="px-4 py-3">Coverage</th><th className="px-4 py-3">Quality</th><th className="px-4 py-3">Hours</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{deckRows.map((deck) => <tr className="border-b border-line last:border-0" key={deck[0]}><td className="px-4 py-3 font-mono text-xs font-bold text-accent">{deck[0]}</td><td className="px-4 py-3 font-bold">{deck[1]}</td><td className="px-4 py-3 text-muted">{deck[2]}</td><td className="px-4 py-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">{deck[3]}</span></td><td className="px-4 py-3 text-muted">{deck[4]}</td><td className="px-4 py-3"><span className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-700"><span className="size-1.5 rounded-full bg-emerald-500" />Available</span></td></tr>)}</tbody></table></div></section>

      <section className="border-y border-line bg-[#edf4ff]" id="api"><div className="mx-auto grid max-w-7xl gap-5 px-4 py-12 sm:px-6 lg:grid-cols-[0.9fr_1.1fr] lg:px-8"><div className="grid content-start gap-4"><p className="text-sm font-extrabold uppercase text-accent">Quality intelligence</p><h2 className="text-3xl font-black leading-tight sm:text-4xl">Evidence your team can inspect, not just a score to accept.</h2><p className="leading-relaxed text-muted">Voice Stream brings scoring, confidence, consensus, and independent subscriber validation into the data-selection workflow.</p><Link className="inline-flex w-fit items-center gap-2 text-sm font-extrabold text-accent no-underline hover:text-accent-dark" href="/register">Request access <ArrowRight aria-hidden="true" className="size-4" /></Link></div><div className="grid gap-3 sm:grid-cols-3"><Metric icon={CheckCircle2} label="Consensus score" value="Multi-signal" text="Quality evidence aggregated from available validation sources." /><Metric icon={BarChart3} label="Confidence" value="Visible" text="Understand the strength of each recording's quality signal." /><Metric icon={FileCheck2} label="Validation history" value="Auditable" text="Review independent validation activity across organizations." /></div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-5 rounded-xl bg-[#0a2e68] p-6 text-white shadow-[0_18px_35px_rgba(7,38,88,0.22)] lg:grid-cols-[0.8fr_1.2fr] lg:p-8"><div><p className="text-sm font-extrabold uppercase text-cyan-200">Enterprise-grade security</p><h2 className="mt-2 text-3xl font-black leading-tight">Control how your organization finds and uses voice data.</h2><p className="mt-3 max-w-lg leading-relaxed text-slate-200">Security controls are designed into the platform, from scoped API credentials through activity visibility and organization roles.</p></div><div className="grid gap-3 sm:grid-cols-2"><SecurityItem icon={LockKeyhole} title="Protected streaming" text="Encrypted delivery with controlled access to licensed data." /><SecurityItem icon={KeyRound} title="Scoped API keys" text="Create, rotate, and revoke credentials for each integration." /><SecurityItem icon={UsersRound} title="Organization roles" text="Give teams only the access required for their work." /><SecurityItem icon={Webhook} title="Event webhooks" text="Integrate deck and billing events with your systems." /></div></div></section>

      <section className="border-t border-line bg-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-4 py-12 sm:px-6 md:flex-row md:items-end lg:px-8"><div><p className="text-sm font-extrabold uppercase text-accent">Pricing</p><h2 className="mt-2 text-3xl font-black">Choose the access your team needs.</h2><p className="mt-2 max-w-2xl leading-relaxed text-muted">Start with the plan that fits your coverage, validation, and delivery needs. Review plan details before creating your organization.</p></div><Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-accent px-5 py-3 font-extrabold text-white no-underline hover:bg-accent-dark" href="/pricing">View pricing <ArrowRight aria-hidden="true" className="size-4" /></Link></div></section>

      <footer className="bg-[#061632] text-slate-300"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 md:grid-cols-[1.4fr_repeat(3,1fr)] lg:px-8"><div className="grid gap-3"><BrandLogo className="text-lg text-white" href="" size={34} /><p className="max-w-sm text-sm leading-relaxed">Licensed voice data infrastructure for teams building speech and language technology with broader coverage.</p></div><FooterColumn title="Product" links={[['Features','/#features'],['Stream Decks','/#stream-decks'],['Validation','/#validation'],['Pricing','/pricing']]} /><FooterColumn title="Developers" links={[['API access','/#api'],['Request access','/register']]} /><FooterColumn title="Account" links={[['Request access','/register'],['Sign in','/login'],['Dashboard','/dashboard'],['Dialect Library','https://www.dialectlibrary.com']]} /></div><div className="border-t border-white/10 px-4 py-5 text-center text-xs text-slate-400">© {new Date().getFullYear()} Dialect Library Voice Stream. All rights reserved.</div></footer>
    </main>
  );
}

function ValueLine({ label, value }: { label: string; value: string }) { return <div className="border-l border-cyan-300/40 pl-3"><p className="text-xs font-extrabold text-cyan-200">{label}</p><p className="mt-1 leading-snug">{value}</p></div>; }
function Step({ number, icon: Icon, title, text }: { number: string; icon: LucideIcon; title: string; text: string }) { return <article className="grid gap-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-accent text-sm font-black text-white">{number}</span><span className="grid size-10 place-items-center rounded-lg bg-accent-soft text-accent"><Icon aria-hidden="true" className="size-5" /></span></div><h3 className="font-black">{title}</h3><p className="text-sm leading-relaxed text-muted">{text}</p></article>; }
function Metric({ icon: Icon, label, value, text }: { icon: LucideIcon; label: string; value: string; text: string }) { return <article className="grid content-start gap-3 rounded-lg border border-line bg-white p-4"><Icon aria-hidden="true" className="size-5 text-accent" /><p className="text-sm font-bold text-muted">{label}</p><p className="text-2xl font-black">{value}</p><p className="text-sm leading-relaxed text-muted">{text}</p></article>; }
function SecurityItem({ icon: Icon, title, text }: { icon: LucideIcon; title: string; text: string }) { return <div className="grid gap-2 rounded-lg border border-white/15 bg-white/5 p-4"><Icon aria-hidden="true" className="size-5 text-cyan-200" /><p className="font-extrabold">{title}</p><p className="text-sm leading-relaxed text-slate-200">{text}</p></div>; }
function FooterColumn({ title, links }: { title: string; links: [string, string][] }) { return <div className="grid content-start gap-2"><p className="font-extrabold text-white">{title}</p>{links.map(([label, href]) => <Link className="w-fit text-sm text-slate-300 no-underline hover:text-cyan-200" href={href} key={label}>{label}</Link>)}</div>; }
