-- AlterEnum
ALTER TYPE "ActivityEventType" ADD VALUE 'DECK_CREATED';
ALTER TYPE "ActivityEventType" ADD VALUE 'DECK_RENAMED';
ALTER TYPE "ActivityEventType" ADD VALUE 'DECK_DELETED';
ALTER TYPE "ActivityEventType" ADD VALUE 'DECK_ITEM_ADDED';
ALTER TYPE "ActivityEventType" ADD VALUE 'DECK_ITEM_REMOVED';
ALTER TYPE "ActivityEventType" ADD VALUE 'DECK_VISIBILITY_CHANGED';
