import type { CountrySeed } from './africa-countries-dialects';

/**
 * Asian coverage for onboarding and the public coverage directory.
 * Dialect.tag is globally unique, so every tag is country-scoped even when
 * the same language is spoken in several countries.
 */
export const ASIA_COUNTRIES: CountrySeed[] = [
  { code: 'AF', name: 'Afghanistan', dialects: [{ tag: 'prs-af', name: 'Dari' }, { tag: 'ps-af', name: 'Pashto' }, { tag: 'uz-af', name: 'Uzbek' }, { tag: 'tk-af', name: 'Turkmen' }] },
  { code: 'AM', name: 'Armenia', dialects: [{ tag: 'hy-am', name: 'Armenian' }, { tag: 'ru-am', name: 'Russian' }] },
  { code: 'AZ', name: 'Azerbaijan', dialects: [{ tag: 'az-az', name: 'Azerbaijani' }, { tag: 'lez-az', name: 'Lezgian' }, { tag: 'tal-az', name: 'Talysh' }, { tag: 'ru-az', name: 'Russian' }] },
  { code: 'BH', name: 'Bahrain', dialects: [{ tag: 'ar-bh', name: 'Arabic (Bahraini)' }, { tag: 'en-bh', name: 'English' }] },
  { code: 'BD', name: 'Bangladesh', dialects: [{ tag: 'bn-bd', name: 'Bengali' }, { tag: 'syl-bd', name: 'Sylheti' }, { tag: 'ctg-bd', name: 'Chittagonian' }, { tag: 'rki-bd', name: 'Rohingya' }] },
  { code: 'BT', name: 'Bhutan', dialects: [{ tag: 'dz-bt', name: 'Dzongkha' }, { tag: 'ne-bt', name: 'Nepali' }, { tag: 'tsh-bt', name: 'Tshangla' }] },
  { code: 'BN', name: 'Brunei', dialects: [{ tag: 'ms-bn', name: 'Malay (Brunei)' }, { tag: 'ked-bn', name: 'Kedayan' }, { tag: 'zh-bn', name: 'Chinese' }, { tag: 'en-bn', name: 'English' }] },
  { code: 'KH', name: 'Cambodia', dialects: [{ tag: 'km-kh', name: 'Khmer' }, { tag: 'cja-kh', name: 'Western Cham' }, { tag: 'mnw-kh', name: 'Mon' }] },
  { code: 'CN', name: 'China', dialects: [{ tag: 'cmn-cn', name: 'Mandarin Chinese' }, { tag: 'yue-cn', name: 'Cantonese' }, { tag: 'wuu-cn', name: 'Wu Chinese' }, { tag: 'nan-cn', name: 'Southern Min' }, { tag: 'hak-cn', name: 'Hakka Chinese' }, { tag: 'ug-cn', name: 'Uyghur' }, { tag: 'bo-cn', name: 'Tibetan' }] },
  { code: 'CY', name: 'Cyprus', dialects: [{ tag: 'el-cy', name: 'Greek (Cypriot)' }, { tag: 'tr-cy', name: 'Turkish (Cypriot)' }] },
  { code: 'GE', name: 'Georgia', dialects: [{ tag: 'ka-ge', name: 'Georgian' }, { tag: 'az-ge', name: 'Azerbaijani' }, { tag: 'hy-ge', name: 'Armenian' }, { tag: 'ru-ge', name: 'Russian' }] },
  { code: 'HK', name: 'Hong Kong', dialects: [{ tag: 'yue-hk', name: 'Cantonese' }, { tag: 'en-hk', name: 'English' }, { tag: 'cmn-hk', name: 'Mandarin Chinese' }] },
  { code: 'IN', name: 'India', dialects: [{ tag: 'hi-in', name: 'Hindi' }, { tag: 'bn-in', name: 'Bengali' }, { tag: 'te-in', name: 'Telugu' }, { tag: 'mr-in', name: 'Marathi' }, { tag: 'ta-in', name: 'Tamil' }, { tag: 'ur-in', name: 'Urdu' }, { tag: 'gu-in', name: 'Gujarati' }, { tag: 'kn-in', name: 'Kannada' }, { tag: 'ml-in', name: 'Malayalam' }, { tag: 'or-in', name: 'Odia' }, { tag: 'pa-in', name: 'Punjabi' }, { tag: 'as-in', name: 'Assamese' }] },
  { code: 'ID', name: 'Indonesia', dialects: [{ tag: 'id-id', name: 'Indonesian' }, { tag: 'jv-id', name: 'Javanese' }, { tag: 'su-id', name: 'Sundanese' }, { tag: 'min-id', name: 'Minangkabau' }, { tag: 'mad-id', name: 'Madurese' }] },
  { code: 'IR', name: 'Iran', dialects: [{ tag: 'fa-ir', name: 'Persian' }, { tag: 'az-ir', name: 'Azerbaijani' }, { tag: 'ku-ir', name: 'Kurdish' }, { tag: 'glk-ir', name: 'Gilaki' }, { tag: 'lrc-ir', name: 'Luri' }] },
  { code: 'IQ', name: 'Iraq', dialects: [{ tag: 'ar-iq', name: 'Arabic (Iraqi)' }, { tag: 'ku-iq', name: 'Kurdish' }, { tag: 'syr-iq', name: 'Assyrian Neo-Aramaic' }, { tag: 'tk-iq', name: 'Turkmen' }] },
  { code: 'IL', name: 'Israel', dialects: [{ tag: 'he-il', name: 'Hebrew' }, { tag: 'ar-il', name: 'Arabic' }, { tag: 'yi-il', name: 'Yiddish' }] },
  { code: 'JP', name: 'Japan', dialects: [{ tag: 'ja-jp', name: 'Japanese' }, { tag: 'ryu-jp', name: 'Okinawan' }, { tag: 'ain-jp', name: 'Ainu' }] },
  { code: 'JO', name: 'Jordan', dialects: [{ tag: 'ar-jo', name: 'Arabic (Jordanian)' }, { tag: 'ady-jo', name: 'Adyghe' }] },
  { code: 'KZ', name: 'Kazakhstan', dialects: [{ tag: 'kk-kz', name: 'Kazakh' }, { tag: 'ru-kz', name: 'Russian' }, { tag: 'uz-kz', name: 'Uzbek' }] },
  { code: 'KW', name: 'Kuwait', dialects: [{ tag: 'ar-kw', name: 'Arabic (Kuwaiti)' }, { tag: 'en-kw', name: 'English' }] },
  { code: 'KG', name: 'Kyrgyzstan', dialects: [{ tag: 'ky-kg', name: 'Kyrgyz' }, { tag: 'ru-kg', name: 'Russian' }, { tag: 'uz-kg', name: 'Uzbek' }] },
  { code: 'LA', name: 'Laos', dialects: [{ tag: 'lo-la', name: 'Lao' }, { tag: 'hmn-la', name: 'Hmong' }, { tag: 'kjg-la', name: 'Khmu' }] },
  { code: 'LB', name: 'Lebanon', dialects: [{ tag: 'ar-lb', name: 'Arabic (Lebanese)' }, { tag: 'fr-lb', name: 'French' }, { tag: 'hy-lb', name: 'Armenian' }] },
  { code: 'MO', name: 'Macao', dialects: [{ tag: 'yue-mo', name: 'Cantonese' }, { tag: 'pt-mo', name: 'Portuguese' }, { tag: 'cmn-mo', name: 'Mandarin Chinese' }] },
  { code: 'MY', name: 'Malaysia', dialects: [{ tag: 'ms-my', name: 'Malay' }, { tag: 'zh-my', name: 'Chinese' }, { tag: 'ta-my', name: 'Tamil' }, { tag: 'iban-my', name: 'Iban' }] },
  { code: 'MV', name: 'Maldives', dialects: [{ tag: 'dv-mv', name: 'Dhivehi' }] },
  { code: 'MN', name: 'Mongolia', dialects: [{ tag: 'mn-mn', name: 'Mongolian' }, { tag: 'kk-mn', name: 'Kazakh' }, { tag: 'bua-mn', name: 'Buryat' }] },
  { code: 'MM', name: 'Myanmar', dialects: [{ tag: 'my-mm', name: 'Burmese' }, { tag: 'shn-mm', name: 'Shan' }, { tag: 'ksw-mm', name: "S'gaw Karen" }, { tag: 'kac-mm', name: 'Jingpho' }] },
  { code: 'NP', name: 'Nepal', dialects: [{ tag: 'ne-np', name: 'Nepali' }, { tag: 'mai-np', name: 'Maithili' }, { tag: 'bho-np', name: 'Bhojpuri' }, { tag: 'new-np', name: 'Newar' }, { tag: 'thl-np', name: 'Tharu' }] },
  { code: 'KP', name: 'North Korea', dialects: [{ tag: 'ko-kp', name: 'Korean (North)' }] },
  { code: 'OM', name: 'Oman', dialects: [{ tag: 'ar-om', name: 'Arabic (Omani)' }, { tag: 'bal-om', name: 'Balochi' }, { tag: 'shv-om', name: 'Shehri' }] },
  { code: 'PK', name: 'Pakistan', dialects: [{ tag: 'ur-pk', name: 'Urdu' }, { tag: 'pa-pk', name: 'Punjabi' }, { tag: 'sd-pk', name: 'Sindhi' }, { tag: 'ps-pk', name: 'Pashto' }, { tag: 'bal-pk', name: 'Balochi' }] },
  { code: 'PS', name: 'Palestine', dialects: [{ tag: 'ar-ps', name: 'Arabic (Palestinian)' }, { tag: 'he-ps', name: 'Hebrew' }] },
  { code: 'PH', name: 'Philippines', dialects: [{ tag: 'fil-ph', name: 'Filipino' }, { tag: 'ceb-ph', name: 'Cebuano' }, { tag: 'ilo-ph', name: 'Ilocano' }, { tag: 'hil-ph', name: 'Hiligaynon' }, { tag: 'war-ph', name: 'Waray' }] },
  { code: 'QA', name: 'Qatar', dialects: [{ tag: 'ar-qa', name: 'Arabic (Qatari)' }, { tag: 'en-qa', name: 'English' }] },
  { code: 'SA', name: 'Saudi Arabia', dialects: [{ tag: 'ars-sa', name: 'Arabic (Najdi)' }, { tag: 'acw-sa', name: 'Arabic (Hejazi)' }, { tag: 'afb-sa', name: 'Arabic (Gulf)' }] },
  { code: 'SG', name: 'Singapore', dialects: [{ tag: 'en-sg', name: 'English (Singapore)' }, { tag: 'zh-sg', name: 'Chinese' }, { tag: 'ms-sg', name: 'Malay' }, { tag: 'ta-sg', name: 'Tamil' }] },
  { code: 'KR', name: 'South Korea', dialects: [{ tag: 'ko-kr', name: 'Korean' }, { tag: 'jje-kr', name: 'Jeju' }] },
  { code: 'LK', name: 'Sri Lanka', dialects: [{ tag: 'si-lk', name: 'Sinhala' }, { tag: 'ta-lk', name: 'Tamil (Sri Lanka)' }] },
  { code: 'SY', name: 'Syria', dialects: [{ tag: 'ar-sy', name: 'Arabic (Syrian)' }, { tag: 'ku-sy', name: 'Kurdish' }, { tag: 'syr-sy', name: 'Syriac' }] },
  { code: 'TW', name: 'Taiwan', dialects: [{ tag: 'cmn-tw', name: 'Mandarin Chinese' }, { tag: 'nan-tw', name: 'Taiwanese Hokkien' }, { tag: 'hak-tw', name: 'Hakka Chinese' }] },
  { code: 'TJ', name: 'Tajikistan', dialects: [{ tag: 'tg-tj', name: 'Tajik' }, { tag: 'uz-tj', name: 'Uzbek' }, { tag: 'ru-tj', name: 'Russian' }] },
  { code: 'TH', name: 'Thailand', dialects: [{ tag: 'th-th', name: 'Thai' }, { tag: 'nod-th', name: 'Northern Thai' }, { tag: 'tts-th', name: 'Isan' }, { tag: 'ms-th', name: 'Malay (Southern Thailand)' }] },
  { code: 'TL', name: 'Timor-Leste', dialects: [{ tag: 'tet-tl', name: 'Tetum' }, { tag: 'pt-tl', name: 'Portuguese' }, { tag: 'mak-tl', name: 'Makasae' }] },
  { code: 'TR', name: 'Turkey', dialects: [{ tag: 'tr-tr', name: 'Turkish' }, { tag: 'ku-tr', name: 'Kurdish' }, { tag: 'zza-tr', name: 'Zaza' }, { tag: 'ar-tr', name: 'Arabic' }] },
  { code: 'TM', name: 'Turkmenistan', dialects: [{ tag: 'tk-tm', name: 'Turkmen' }, { tag: 'ru-tm', name: 'Russian' }, { tag: 'uz-tm', name: 'Uzbek' }] },
  { code: 'AE', name: 'United Arab Emirates', dialects: [{ tag: 'ar-ae', name: 'Arabic (Emirati)' }, { tag: 'en-ae', name: 'English' }] },
  { code: 'UZ', name: 'Uzbekistan', dialects: [{ tag: 'uz-uz', name: 'Uzbek' }, { tag: 'ru-uz', name: 'Russian' }, { tag: 'kaa-uz', name: 'Karakalpak' }, { tag: 'tg-uz', name: 'Tajik' }] },
  { code: 'VN', name: 'Vietnam', dialects: [{ tag: 'vi-vn', name: 'Vietnamese' }, { tag: 'tyz-vn', name: 'Tay' }, { tag: 'hmn-vn', name: 'Hmong' }, { tag: 'ngt-vn', name: 'Nung' }] },
  { code: 'YE', name: 'Yemen', dialects: [{ tag: 'ar-ye', name: 'Arabic (Yemeni)' }, { tag: 'gdq-ye', name: 'Mehri' }, { tag: 'sqt-ye', name: 'Soqotri' }] },
];
