'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Plus, Search } from 'lucide-react';
import { AdminShell } from '@/components/admin/AdminShell';
import { ActionButton } from '@/components/ui/ActionButton';
import { Dialog, DialogClose, DialogContent, DialogTrigger } from '@/components/ui/Dialog';
import {
  DomainPromptGenderVariant,
  normalizeErrorMessage,
  useCreateDomainPromptAdminMutation,
  useDeleteDomainPromptAdminMutation,
  useGetAdminDomainPromptDomainsQuery,
  useGetAdminDomainPromptsQuery,
  useSetDomainPromptDisabledAdminMutation,
  useUpdateDomainPromptAdminMutation,
} from '@/store/api';

const secondaryButtonClass =
  'inline-flex min-h-9 items-center justify-center rounded-lg border border-line bg-surface px-3 py-1.5 text-sm font-bold text-ink transition-colors hover:bg-surface-muted disabled:cursor-not-allowed disabled:opacity-60';
const dangerButtonClass =
  'inline-flex min-h-9 items-center justify-center rounded-lg border border-line bg-surface px-3 py-1.5 text-sm font-bold text-danger transition-colors hover:bg-[#fde8e8] disabled:cursor-not-allowed disabled:opacity-60';
const primaryButtonClass =
  'inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-accent bg-accent px-3.5 py-2.5 font-bold text-white transition-colors hover:bg-accent-dark disabled:cursor-not-allowed disabled:opacity-60';
const inputClass =
  'min-h-10 w-full rounded-lg border border-line bg-white px-3 py-2 text-ink dark:bg-surface-muted';

const genderVariantLabels: Record<DomainPromptGenderVariant, string> = {
  NEUTRAL: 'Neutral',
  MALE: 'Male',
  FEMALE: 'Female',
};

function useDebouncedValue<T>(value: T, delayMs: number): T {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => {
    const timer = setTimeout(() => setDebounced(value), delayMs);
    return () => clearTimeout(timer);
  }, [value, delayMs]);
  return debounced;
}

export default function AdminDomainPromptsPage() {
  const [showDisabled, setShowDisabled] = useState(false);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [domain, setDomain] = useState('');
  const [genderVariant, setGenderVariant] = useState<DomainPromptGenderVariant | ''>('');
  const debouncedSearch = useDebouncedValue(search, 300);
  const pageSize = 20;

  const { data: domains } = useGetAdminDomainPromptDomainsQuery();
  const { data, isLoading, isFetching, isError, refetch } = useGetAdminDomainPromptsQuery({
    page,
    pageSize,
    search: debouncedSearch || undefined,
    domain: domain || undefined,
    genderVariant: genderVariant || undefined,
    disabled: showDisabled,
  });
  const [setDisabled] = useSetDomainPromptDisabledAdminMutation();
  const [deletePrompt] = useDeleteDomainPromptAdminMutation();
  const [error, setError] = useState<string | null>(null);
  const [togglingId, setTogglingId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);

  useEffect(() => {
    setPage(1);
  }, [debouncedSearch, domain, genderVariant, showDisabled]);

  async function handleToggleDisabled(id: string, nextDisabled: boolean) {
    setError(null);
    setTogglingId(id);
    try {
      await setDisabled({ id, disabled: nextDisabled }).unwrap();
    } catch (err) {
      setError(
        normalizeErrorMessage(err, nextDisabled ? 'Unable to disable prompt.' : 'Unable to enable prompt.'),
      );
    } finally {
      setTogglingId(null);
    }
  }

  async function handleDelete(id: string) {
    setError(null);
    setDeletingId(id);
    try {
      await deletePrompt(id).unwrap();
    } catch (err) {
      setError(normalizeErrorMessage(err, 'Unable to delete prompt.'));
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <AdminShell>
      <div className="grid gap-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="grid gap-2">
            <h1 className="text-3xl font-black">Domain Conversation Prompts</h1>
            <p className="max-w-2xl leading-relaxed text-muted">
              Scenario prompts bulk-generated by the domain-conversation-prompt-job (see Settings
              &rarr; Domain Conversation), pooled and served round-robin to trainers. Disable a
              scenario to pull it out of the pool without losing existing recordings; delete only
              removes ones with no history left to protect.
            </p>
          </div>
          <Dialog onOpenChange={setCreateOpen} open={createOpen}>
            <DialogTrigger asChild>
              <button className={primaryButtonClass} type="button">
                <Plus className="size-4" aria-hidden="true" />
                Add scenario
              </button>
            </DialogTrigger>
            <DialogContent
              description="Creates all three gender variants (Neutral/Male/Female) for one scenario."
              title="Add a scenario"
            >
              <CreatePromptForm onClose={() => setCreateOpen(false)} />
            </DialogContent>
          </Dialog>
        </div>

        <div className="flex gap-1">
          <button
            className={`rounded-lg px-3 py-2 text-sm font-bold transition-colors ${
              !showDisabled ? 'bg-accent text-white' : 'bg-white text-ink hover:bg-surface-muted'
            }`}
            onClick={() => setShowDisabled(false)}
            type="button"
          >
            Active
          </button>
          <button
            className={`rounded-lg px-3 py-2 text-sm font-bold transition-colors ${
              showDisabled ? 'bg-accent text-white' : 'bg-white text-ink hover:bg-surface-muted'
            }`}
            onClick={() => setShowDisabled(true)}
            type="button"
          >
            Disabled
          </button>
        </div>

        <section className="grid gap-4 overflow-hidden rounded-lg border border-line bg-white shadow-[0_2px_8px_rgba(27,31,27,0.05)]">
          <div className="flex flex-wrap items-center gap-3 border-b border-line p-3">
            <div className="relative max-w-sm">
              <Search
                className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"
                aria-hidden="true"
              />
              <input
                aria-label="Search prompts"
                className="min-h-10 w-full rounded-lg border border-line bg-white py-2 pl-9 pr-3 text-sm text-ink dark:bg-surface-muted"
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search prompt text..."
                type="search"
                value={search}
              />
            </div>
            <div className="flex items-center gap-2">
              <label className="text-sm font-bold" htmlFor="domain-filter">
                Domain
              </label>
              <select
                className="min-h-9 rounded-lg border border-line bg-white px-3 text-sm"
                id="domain-filter"
                onChange={(e) => setDomain(e.target.value)}
                value={domain}
              >
                <option value="">All</option>
                {domains?.map((d) => (
                  <option key={d} value={d}>
                    {d}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex items-center gap-2">
              <label className="text-sm font-bold" htmlFor="gender-variant-filter">
                Variant
              </label>
              <select
                className="min-h-9 rounded-lg border border-line bg-white px-3 text-sm"
                id="gender-variant-filter"
                onChange={(e) => setGenderVariant(e.target.value as DomainPromptGenderVariant | '')}
                value={genderVariant}
              >
                <option value="">All</option>
                {(Object.keys(genderVariantLabels) as DomainPromptGenderVariant[]).map((key) => (
                  <option key={key} value={key}>
                    {genderVariantLabels[key]}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {error && (
            <p className="px-5 leading-relaxed text-danger" role="alert">
              {error}
            </p>
          )}

          {isLoading ? (
            <p className="p-5 text-muted">Loading...</p>
          ) : isError ? (
            <div className="grid gap-3 p-5 text-center">
              <p className="font-extrabold">Could not load prompts.</p>
              <button className={secondaryButtonClass} onClick={() => void refetch()} type="button">
                Try again
              </button>
            </div>
          ) : data && data.items.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full min-w-180 border-collapse text-left text-sm">
                <thead className="border-b border-line bg-surface-muted text-xs font-extrabold uppercase text-muted">
                  <tr>
                    <th className="px-5 py-3.5" scope="col">
                      Domain
                    </th>
                    <th className="px-5 py-3.5" scope="col">
                      Variant
                    </th>
                    <th className="px-5 py-3.5" scope="col">
                      Prompt
                    </th>
                    <th className="px-5 py-3.5" scope="col">
                      Times served
                    </th>
                    <th className="px-5 py-3.5" scope="col">
                      Last served
                    </th>
                    <th className="px-5 py-3.5" scope="col">
                      Source
                    </th>
                    <th className="px-5 py-3.5" scope="col">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-line">
                  {data.items.map((prompt) => (
                    <tr key={prompt.id}>
                      <td className="px-5 py-3.5 font-extrabold">{prompt.domain}</td>
                      <td className="px-5 py-3.5 text-muted">
                        {genderVariantLabels[prompt.genderVariant]}
                      </td>
                      <td className="max-w-xs px-5 py-3.5 text-muted">{prompt.text}</td>
                      <td className="px-5 py-3.5 text-muted">{prompt.timesServed}</td>
                      <td className="px-5 py-3.5 text-muted">
                        {prompt.lastServedAt ? new Date(prompt.lastServedAt).toLocaleDateString() : '—'}
                      </td>
                      <td className="px-5 py-3.5 text-muted">{prompt.source}</td>
                      <td className="px-5 py-3.5">
                        <div className="flex flex-wrap gap-2">
                          <ActionButton
                            className={secondaryButtonClass}
                            onClick={() => handleToggleDisabled(prompt.id, !prompt.isDisabled)}
                            pending={togglingId === prompt.id}
                            pendingLabel={prompt.isDisabled ? 'Enabling' : 'Disabling'}
                            type="button"
                          >
                            {prompt.isDisabled ? 'Enable' : 'Disable'}
                          </ActionButton>
                          <ActionButton
                            className={dangerButtonClass}
                            onClick={() => handleDelete(prompt.id)}
                            pending={deletingId === prompt.id}
                            pendingLabel="Deleting"
                            type="button"
                          >
                            Delete
                          </ActionButton>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p className="p-5 text-muted">
              {debouncedSearch
                ? `No prompts match "${debouncedSearch}".`
                : showDisabled
                  ? 'No disabled prompts.'
                  : 'No prompts yet -- enable generation in Settings, or add one manually.'}
            </p>
          )}

          {data && data.totalPages > 1 && (
            <div className="flex items-center justify-between gap-3 border-t border-line bg-surface-muted px-4 py-3 md:px-5">
              <p className="text-sm text-muted">
                Page {data.page} of {data.totalPages} {isFetching ? '· refreshing…' : ''}
              </p>
              <div className="flex gap-2">
                <button
                  className={secondaryButtonClass}
                  disabled={page <= 1}
                  onClick={() => setPage((p) => p - 1)}
                  type="button"
                >
                  Previous
                </button>
                <button
                  className={secondaryButtonClass}
                  disabled={page >= data.totalPages}
                  onClick={() => setPage((p) => p + 1)}
                  type="button"
                >
                  Next
                </button>
              </div>
            </div>
          )}
        </section>
      </div>
    </AdminShell>
  );
}

function CreatePromptForm({ onClose }: { onClose: () => void }) {
  const [createPrompt, { isLoading }] = useCreateDomainPromptAdminMutation();
  const [domain, setDomain] = useState('');
  const [scenarioKey, setScenarioKey] = useState('');
  const [neutralText, setNeutralText] = useState('');
  const [maleText, setMaleText] = useState('');
  const [femaleText, setFemaleText] = useState('');
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();
    setError(null);
    try {
      await createPrompt({
        domain: domain.trim(),
        scenarioKey: scenarioKey.trim(),
        neutralText: neutralText.trim(),
        maleText: maleText.trim(),
        femaleText: femaleText.trim(),
      }).unwrap();
      onClose();
    } catch (err) {
      setError(normalizeErrorMessage(err, 'Unable to create scenario.'));
    }
  }

  return (
    <form className="grid gap-3" onSubmit={handleSubmit}>
      <label className="grid gap-1 text-sm font-bold" htmlFor="new-prompt-domain">
        Domain
        <input
          className={inputClass}
          id="new-prompt-domain"
          onChange={(e) => setDomain(e.target.value)}
          placeholder="Market"
          required
          value={domain}
        />
      </label>
      <label className="grid gap-1 text-sm font-bold" htmlFor="new-prompt-scenario-key">
        Scenario key (unique, kebab-case)
        <input
          className={inputClass}
          id="new-prompt-scenario-key"
          onChange={(e) => setScenarioKey(e.target.value)}
          placeholder="market-buy-rice"
          required
          value={scenarioKey}
        />
      </label>
      <label className="grid gap-1 text-sm font-bold" htmlFor="new-prompt-neutral">
        Neutral variant text
        <textarea
          className={`${inputClass} min-h-20`}
          id="new-prompt-neutral"
          onChange={(e) => setNeutralText(e.target.value)}
          required
          value={neutralText}
        />
      </label>
      <label className="grid gap-1 text-sm font-bold" htmlFor="new-prompt-male">
        Male variant text
        <textarea
          className={`${inputClass} min-h-20`}
          id="new-prompt-male"
          onChange={(e) => setMaleText(e.target.value)}
          required
          value={maleText}
        />
      </label>
      <label className="grid gap-1 text-sm font-bold" htmlFor="new-prompt-female">
        Female variant text
        <textarea
          className={`${inputClass} min-h-20`}
          id="new-prompt-female"
          onChange={(e) => setFemaleText(e.target.value)}
          required
          value={femaleText}
        />
      </label>
      {error && (
        <p className="text-sm font-bold text-danger" role="alert">
          {error}
        </p>
      )}
      <div className="flex justify-end gap-2">
        <DialogClose className={secondaryButtonClass}>Cancel</DialogClose>
        <ActionButton className={primaryButtonClass} pending={isLoading} pendingLabel="Creating" type="submit">
          Create scenario
        </ActionButton>
      </div>
    </form>
  );
}
