apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - postgres.yaml
  - pgadmin.yaml
  - pgadmin-ingress.yaml
  - model-pvc.yaml
  - tts-model-pvc.yaml
  - api-deployment.yaml
  - api-hpa.yaml
  - api-ingress.yaml
  - vosk-worker-deployment.yaml
  - vosk-worker-keda.yaml
  - prompt-audio-service-deployment.yaml
  - prompt-audio-service-keda.yaml
  - consensus-scorer-deployment.yaml
  - consensus-scorer-hpa.yaml
  - settlement-cronjob.yaml
