apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rabbitmq.dialectlibrary.com
      secretName: rabbitmq-management-tls
  rules:
    - host: rabbitmq.dialectlibrary.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-management
                port:
                  number: 15672
