apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vosk-worker-scaler
spec:
  scaleTargetRef:
    name: vosk-worker
  minReplicaCount: 0
  maxReplicaCount: 15
  cooldownPeriod: 120
  pollingInterval: 15
  triggers:
    - type: redis-streams
      metadata:
        address: redis.dai.svc.cluster.local:6379
        stream: asr-jobs
        consumerGroup: asr-workers
        lagCount: "1"
        activationLagCount: "0"
