apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-worker
  labels:
    app: whisper-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: whisper-worker
  template:
    metadata:
      labels:
        app: whisper-worker
    spec:
      containers:
        - name: whisper-worker
          image: golojan/dialect-whisper-worker:latest
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: whisper-worker-config
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: whisper-worker-config
                  key: redis_port
            - name: ASR_STREAM
              valueFrom:
                configMapKeyRef:
                  name: whisper-worker-config
                  key: asr_stream
            - name: CONSENSUS_STREAM
              valueFrom:
                configMapKeyRef:
                  name: whisper-worker-config
                  key: consensus_stream
            - name: CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: whisper-worker-config
                  key: consumer_group
            - name: SPACES_REGION
              valueFrom:
                configMapKeyRef:
                  name: whisper-worker-config
                  key: spaces_region
            - name: SPACES_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: spaces-creds
                  key: endpoint
            - name: SPACES_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-creds
                  key: access_key
            - name: SPACES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-creds
                  key: secret_key
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-creds
                  key: hf_token
            - name: API_TOKEN_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-creds
                  key: api_token_encryption_key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: connection_string
          volumeMounts:
            - name: whisper-model-repo
              mountPath: /models
              readOnly: false
      volumes:
        - name: whisper-model-repo
          persistentVolumeClaim:
            claimName: whisper-model-repo-pvc
